coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        base: auto
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto

comment:
  behavior: default
  layout: "reach, diff, flags, files"
  require_base: true
  require_head: true
  require_changes: false