coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        base: main
    patch:
      default:
        target: 100%
        threshold: 0%

comment:
  layout: "header, files, footer"
  behavior: default
  require_changes: false 
  require_base: false
  require_head: true
  hide_project_coverage: false