coverage:
  status:
    project:
      default:
        enabled: true
        target: 100%
        threshold: 0%
        base: auto
    patch:
      default:
        enabled: true
        target: 100%
        threshold: 0%
        base: auto

comment:
  layout: "header, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false