codecov:
  bot: codecov-io
  ci: [ "github-actions" ]
  disable_default_path_fixes: false
  max_report_age: false
  notify:
    after_n_builds: 2
    wait_for_ci: true
  require_ci_to_pass: true
  strict_yaml_branch: main
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        base: auto
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto