codecov:
  bot: "codecov-io"
  ci: [ "github-actions" ]
  strict_yaml_branch: false
  max_report_age: false
  disable_default_path_fixes: false
  require_ci_to_pass: true
  notify:
    after_n_builds: 2
    wait_for_ci: true

coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        base: auto
        branches: [ "main" ]
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto
        branches: [ "main" ]

comment:
  layout: "diff, flags, files"
  hide_project_coverage: false
