name: Feature or enhancement
description: Submit a feature request or enhancement
labels: ["feature"]

body:
  - type: textarea
    attributes:
      label: "Feature description"
      description: A clear and concise description of what the feature is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Why is this needed"
      description: A clear and concise description of why we need this feature.

  - type: textarea
    attributes:
      label: "Previous discussion"
      description: Link to related issue/PR (if applicable).