name: YAML lint

on:
  push:
    paths: [ "**.yml", "**.yaml" ]
  pull_request:
    paths: [ "**.yml", "**.yaml" ]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: yamllint .
